### ISSUE TITLE
Deep link doesn't work

### ISSUE THREAD

**Issue by junichiro-watanabe** [phantom-labs/deep-link-demo-app#2]
I have already downloaded the phantom app, but it doesn't open in the deep link.
It opens to the AppStore. Please tell me the cause.

https://user-images.githubusercontent.com/64312219/162144190-b4aa91ef-ad23-4b41-b0cc-5f4c051b10c6.MP4

**Comment by junichiro-watanabe** [comment]
I have resolved this issue by rebooting iPhone.

**Comment by junichiro-watanabe** [comment]
But another issue happens. The browse deeplink doesn't work when the phantom app is being closed. However, it works when the phantom app is opening. The deep link is below, and I referenced [this doc](https://docs.phantom.app/integrating/deeplinks/other-methods/browse).
https://phantom.app/ul/browse/https%3A%2F%2Fmagiceden.io%2Fitem-details%2FED8Psf2Zk2HyVGAimSQpFHVDFRGDAkPjQhkfAqbN5h7d?ref=https%3A%2F%2Fmagiceden.io
 Is this a specification?

https://user-images.githubusercontent.com/64312219/162159769-ce690e62-645d-4360-bb1f-9ec6e594c71f.MP4

**Comment by bfriel** [comment]
Hi @junichiro-watanabe thanks for flagging this! This is a bug. We will get this resolved shortly!

**Comment by josh-deprogram** [comment]
I'm experiencing the same original problem reported here that hitting Connect launches the link in Safari and then bounces to the AppStore.  
Any ideas as to what maybe wrong other than restarting the iPhone as this has no effect.

Using on device iPhone 11

**Comment by josh-deprogram** [comment]
Deleting and reinstalling Phantom seems to have resolved that issue

**Comment by NavidHosseini** [comment]
same issue in android, it doesn't open in the deep link,open in play store

**Comment by nazarlitvin** [comment]
Hi guys, experiencing the same problem on android

**Comment by bfriel** [comment]
Hi @NavidHosseini & @nazarlitvin - we're aware of the issue with Android and are working on a fix.

For now, you can get around this by changing the [build URL](https://github.com/phantom-labs/deep-link-demo-app/blob/20f19f2154e98699f0d5a6b28bc4bb3d5acbcefd/App.tsx#L29) to Phantom's custom `phantom://` handler. Specifically, you can change `https://phantom.app/ul` to `phantom://`, keep everything else the same, and the app will work on Android.

We will keep you posted on a fix for the universal link on Android.

**Comment by nazarlitvin** [comment]
Thank you @bfriel

**Comment by bfriel** [comment]
This is now fixed in Phantom `22.5.13`!
