### ISSUE TITLE
Redirect doesn't work in web

### ISSUE THREAD

**Issue by redniche** [phantom-labs/deep-link-demo-app#3]
https://user-images.githubusercontent.com/44011226/163505341-4e90e561-2e15-46af-8f63-723bb7f751b2.mp4

When I run yarn web : `expo start --web` , it doesn't work properly.
Is there any workaround for this problem?

**Comment by redniche** [comment]
> DeepLinkDemoBug.mp4 
> When I run yarn web : `expo start --web` , it doesn't work properly. Is there any workaround for this problem?

It works correctly in the Android App environment. yarn android : `expo start --android`

**Comment by marty-mcflai** [comment]
@redniche You'll need to make sure you handle paths properly, this will redirect to /onConnect on web, but there's no router set up in this demo app. The idea is for you to look through the code and get an understanding of how it works and then implement it in your own app.

**Comment by dohankk** [comment]
@redniche have you solved?

**Comment by redniche** [comment]
> @redniche have you solved this?

https://docs.phantom.app/integrating/deeplinks-ios-and-android/specifying-redirects
See this

**Comment by JupiterXiaoxiaoYu** [comment]
> > @redniche have you solved this?
> 
> https://docs.phantom.app/integrating/deeplinks-ios-and-android/specifying-redirects See this

This is still for ios and android, How to do it for the web? every time my app just goes back to the first page on the web which is not the page that should receive the data (this refreshes the browser using the redirect URL
