### ISSUE TITLE
Android Expo link not working.

### ISSUE THREAD

**Issue by mcpat1993** [phantom-labs/deep-link-demo-app#5]
I ran cloned the repo.
I cd'ed into the directory.
I executed yarn start.
I got the QR code.
I downloaded and installed the Expo Go app.
I scanned the QR code
I get the following message:
![something went wrong](https://user-images.githubusercontent.com/8905548/168144251-61ca99d9-088c-4194-9467-f40c20b36438.png)

I have tried stopping it and yarn starting again but that also didn't work.
I have also restarted the Expo Go app.
There are no error messages in the terminal when 'something went wrong'.
This is the error message on my phone: 
![280245668_555075916180454_6002437582990169757_n](https://user-images.githubusercontent.com/8905548/168144872-2ce3a0fa-b485-449b-9855-1a33b93f7b37.png)

I'm running on an M1 chip: Apple M1 Max
Monterey 12.2.1 (21D62)

My Android phone is Pixel 6

Both devices are on the same Wifi network.

I would appreciate any help getting this running. :D

**Comment by bfriel** [comment]
Hi @mcpat1993  - we're aware of the issue with Android and are working on a fix.

For now, you can get around this by changing the [build URL](https://github.com/phantom-labs/deep-link-demo-app/blob/20f19f2154e98699f0d5a6b28bc4bb3d5acbcefd/App.tsx#L29) to Phantom's custom `phantom://` handler. Specifically, you can change `https://phantom.app/ul` to `phantom://`, keep everything else the same, and the app will work on Android.

We will keep you posted on a fix for the universal link on Android.
